<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netframework4.7.2</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <LangVersion>latest</LangVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <TargetName>Assembly-CSharp.APIPatcher.mm</TargetName>
    </PropertyGroup>

    <PropertyGroup>
        <NoWarn>$(NoWarn);AD0001;CS0612;CS8604;CS0252;CS0618;Harmony003;Publicizer001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Inscryption.GameLibs" Version="1.9.0-r.0" />
      <PackageReference Include="MonoMod" Version="22.7.31.1" />
      <PackageReference Include="UnityEngine.Modules" Version="2019.4.24" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Private="false" Include="..\InscryptionAPI\InscryptionAPI.csproj" />
    </ItemGroup>
</Project>
