### YamlMime:ManagedReference
items:
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo
  commentId: T:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo
  id: EnergyDrone.EnergyConfigInfo
  parent: InscryptionCommunityPatch.ResourceManagers
  children:
  - InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone
  - InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox
  - InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy
  - InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox
  langs:
  - csharp
  - vb
  name: EnergyDrone.EnergyConfigInfo
  nameWithType: EnergyDrone.EnergyConfigInfo
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo
  type: Class
  source:
    remote:
      path: InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
      branch: patch-7
      repo: https://github.com/xhayper/InscryptionAPI
    id: EnergyConfigInfo
    path: ../InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
    startLine: 12
  assemblies:
  - InscryptionCommunityPatch
  namespace: InscryptionCommunityPatch.ResourceManagers
  syntax:
    content: public class EnergyConfigInfo
    content.vb: Public Class EnergyConfigInfo
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy
  commentId: P:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy
  id: ConfigEnergy
  parent: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo
  langs:
  - csharp
  - vb
  name: ConfigEnergy
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigEnergy
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy
  type: Property
  source:
    remote:
      path: InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
      branch: patch-7
      repo: https://github.com/xhayper/InscryptionAPI
    id: ConfigEnergy
    path: ../InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
    startLine: 15
  assemblies:
  - InscryptionCommunityPatch
  namespace: InscryptionCommunityPatch.ResourceManagers
  syntax:
    content: public bool ConfigEnergy { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ConfigEnergy As Boolean
  overload: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone
  commentId: P:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone
  id: ConfigDrone
  parent: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo
  langs:
  - csharp
  - vb
  name: ConfigDrone
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigDrone
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone
  type: Property
  source:
    remote:
      path: InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
      branch: patch-7
      repo: https://github.com/xhayper/InscryptionAPI
    id: ConfigDrone
    path: ../InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
    startLine: 25
  assemblies:
  - InscryptionCommunityPatch
  namespace: InscryptionCommunityPatch.ResourceManagers
  syntax:
    content: public bool ConfigDrone { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ConfigDrone As Boolean
  overload: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox
  commentId: P:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox
  id: ConfigMox
  parent: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo
  langs:
  - csharp
  - vb
  name: ConfigMox
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigMox
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox
  type: Property
  source:
    remote:
      path: InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
      branch: patch-7
      repo: https://github.com/xhayper/InscryptionAPI
    id: ConfigMox
    path: ../InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
    startLine: 35
  assemblies:
  - InscryptionCommunityPatch
  namespace: InscryptionCommunityPatch.ResourceManagers
  syntax:
    content: public bool ConfigMox { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ConfigMox As Boolean
  overload: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox
  commentId: P:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox
  id: ConfigDroneMox
  parent: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo
  langs:
  - csharp
  - vb
  name: ConfigDroneMox
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigDroneMox
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox
  type: Property
  source:
    remote:
      path: InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
      branch: patch-7
      repo: https://github.com/xhayper/InscryptionAPI
    id: ConfigDroneMox
    path: ../InscryptionCommunityPatch/ResourceManagers/ActOneEnergyDrone.cs
    startLine: 45
  assemblies:
  - InscryptionCommunityPatch
  namespace: InscryptionCommunityPatch.ResourceManagers
  syntax:
    content: public bool ConfigDroneMox { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ConfigDroneMox As Boolean
  overload: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: InscryptionCommunityPatch.ResourceManagers
  commentId: N:InscryptionCommunityPatch.ResourceManagers
  name: InscryptionCommunityPatch.ResourceManagers
  nameWithType: InscryptionCommunityPatch.ResourceManagers
  fullName: InscryptionCommunityPatch.ResourceManagers
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy*
  commentId: Overload:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy
  name: ConfigEnergy
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigEnergy
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigEnergy
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone*
  commentId: Overload:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone
  name: ConfigDrone
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigDrone
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDrone
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox*
  commentId: Overload:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox
  name: ConfigMox
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigMox
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigMox
- uid: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox*
  commentId: Overload:InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox
  name: ConfigDroneMox
  nameWithType: EnergyDrone.EnergyConfigInfo.ConfigDroneMox
  fullName: InscryptionCommunityPatch.ResourceManagers.EnergyDrone.EnergyConfigInfo.ConfigDroneMox
